### ISSUE TITLE
Flux atom valide à 100%.

### ISSUE THREAD

**Issue by Debetux** [quent1-fr/Atomic-Bird#3]
Hey,

C'est presque impossible de faire un flux atom valide (peut être que ça ne sert à rien, mais c'est mieux un truc clean). J'ai cherché partout, mais je n'ai pas trouvé. J'ai essayé les méthodes utilisées par Wordpress (je ne sais pas si il génère un flux valide en fait), ou bien shaarli, mais sans succès. Ca provient des caractères du type \x80, etc..

Vous avez pas une petite idée ?

**Comment by quent1-fr** [comment]
Qu'entends-tu exactement par « flux valide »?
